lidars:
  front:
    namespace: "lidar_front"
    frame_id: "hokuyo_lidar"
    angle_max: 2.0923497676849365
    angle_min: -2.0923497676849365
    description: "Front lidar configuration"
  
  rear:
    namespace: "lidar_rear"
    frame_id: "lidar_rear_frame"
    angle_max: 2.0923497676849365
    angle_min: -2.0923497676849365
    description: "Rear lidar configuration"

merger_params:
  target_frame: "hokuyo_lidar"
  output_topic: "/merged_scan"
  # front_lidar_frame: 'lidar_front_frame'
  # rear_lidar_frame: 'lidar_rear_frame'
  front_topic: '/my_robot/hokuyo_lidar'    # '/right_gazebo_ros_ray_sensor/out',
  rear_topic: '/lidar_rear/scan'      # '/left_gazebo_ros_ray_sensor/out',
  angle_max: 3.14
  angle_min: -3.14
  angle_increment: 0.006135923322290182
  range_min: 0.1
  range_max: 10.0
  transform_timeout: 0.1
  enable_duplicate_filter: False
  duplicate_filter_distance: 0.02
